export const events = [
  {
    id: 1,
    slug: "bitcoin-summit-ethiopia-2024-dahab-miners-sponsorship",
    imglg: "/home/bitcoin-summit-lg.webp",
    imgsm: "/home/bitcoin-summit-lg.webp",
    alt: "Dahab Miners team speaking at Bitcoin Summit Addis Ababa 2024, promoting sustainable Bitcoin mining powered by renewable energy in Ethiopia.",
    title: "BITCOIN SUMMIT",
    date: "november 28, 2024",
    location: "Addis Ababa, Ethiopia",
    p1: "Dahab Miners proudly sponsors the Bitcoin Summit in Addis Ababa, Ethiopia — November 28,2024",
    p2: "On November 28, 2024, Dahab Miners proudly participated as a co-sponsor at the Bitcoin Summit held at the Sheraton Hotel in Addis Ababa, Ethiopia, marking a major milestone in Africa’s growing role in the global Bitcoin mining landscape.",
    p3: "The landmark event brought together leaders and visionaries from across the cryptocurrency, blockchain, and digital finance industries. Featuring a dynamic lineup of speakers — from technologists and entrepreneurs to policy advocates — the summit focused on Bitcoin’s potential to drive financial inclusion, empower local economies, and foster digital transformation across the continent. ",
    p4: "Dahab Miners’ sponsorship underscored our deep commitment to advancing sustainable mining solutions and supporting Ethiopia’s ambition to emerge as a key hub in the global crypto economy. Through productive discussions and networking with fellow innovators, Dahab Miners took an active role in shaping the future of Bitcoin mining in Africa.",
    p5: "In a historic moment at the event, Dahab Miners officially announced its 10MW procurement initiative in Ethiopia, reinforcing our long-term investment in the country’s energy and mining sectors. This project represents a major step forward in establishing large-scale, efficient mining operations powered by Ethiopia’s abundant renewable energy resources. ",
    p6: "Our participation at the Bitcoin Summit in Addis Ababa reflects Dahab Miners’ vision of powering the future — one block at a time — by fostering innovation, transparency, and inclusive growth in Africa’s digital economy. ",
  },
  {
    id: 2,
    slug: "mining-roundtable-conference-abu-dhabi-2024",
    imglg: "/home/annual-team-meeting-new-lg.webp",
    imgsm: "/home/annual-team-meeting-new-sm.webp",
    alt: "Dahab Miners team at the Mining Roundtable Conference 2024 in Abu Dhabi, fostering discussions on sustainable Bitcoin mining and blockchain innovation in the Middle East.",
    title: "MINING ROUND TABLE CONFERENCE",
    date: "december 10, 2024",
    location: "Abu Dhabi, United Arab Emirates",
    p1: "On December 10, 2024, Dahab Miners proudly sponsored the Mining Roundtable, an exclusive side event held during the Bitcoin MENA 2024 conference at the Abu Dhabi National Exhibition Centre (ADNEC). Organized by the Bitcoin Association Arabia, this intimate gathering brought together policymakers, industry leaders, and innovators to discuss the evolving regulatory landscape and strategic opportunities in the Bitcoin mining sector",
    p2: "The Mining Roundtable served as a platform for high-level dialogue on the future of Bitcoin mining in the Middle East, focusing on sustainable practices, energy utilization, and regional collaboration. Dahab Miners’ sponsorship underscored our commitment to fostering meaningful conversations that drive innovation and growth within the industry",
    p3: "This event complemented the broader Bitcoin MENA 2024 conference, which featured a diverse lineup of speakers and attracted attendees from over 88 countries, highlighting Abu Dhabi’s emergence as a global hub for cryptocurrency and blockchain innovation.",
    p4: "Dahab Miners is honored to have contributed to this pivotal moment in the region’s Bitcoin journey, reinforcing our dedication to advancing the mining sector through strategic partnerships and knowledge exchange",
    p5: "",
  },
  {
    id: 3,
    slug: "bitcoin-oasis-2025-dubai-dahab-miners-sponsorship",
    imglg: "/home/bitcoin-oasis-lg.webp",
    imgsm: "/home/bitcoin-oasis-sm.webp",
    alt: "Dahab Miners sponsoring Bitcoin Oasis 2025 at Museum of the Future, Dubai - featuring Rizwan Kamarudheen discussing full-stack Bitcoin mining innovation",
    title: "BITCOIN OASIS FROM GRIDLOCK TO FULL STACK",
    date: " april 28-29 2025",
    location: "museum of the future, dubai, United Arab Emirates",
    p1: "On April 28–29, 2025, Dahab Miners proudly sponsored Bitcoin Oasis, an exclusive Bitcoin-focused conference held at the iconic Museum of the Future in Dubai. Organized by Bitcoin Arabia, the event convened leading voices in Bitcoin infrastructure, policy, and investment from across the Middle East and beyond",
    p2: "Dahab Miners’ co-founder, Rizwan Kamarudheen, was featured as a speaker, delivering a talk titled “From Gridlock to Full Stack Mining.” Drawing from his experience leading mining infrastructure projects in the UAE and Ethiopia, Rizwan shared insights on building scalable, end-to-end mining operations in emerging energy markets. His presentation highlighted Dahab Miners’ commitment to sustainable growth and innovation in the Bitcoin mining sector",
    p3: "Bitcoin Oasis 2025 served as a strategic platform for industry leaders, investors, and policymakers to explore the future of Bitcoin in the Gulf region. Dahab Miners’ participation underscored our dedication to advancing the Bitcoin ecosystem through collaboration, innovation, and regional partnerships.",
    p4: "",
    p5: "",
  },
  {
    id: 4,
    slug: "dahab-miners-annual-team-meeting-abu-dhabi-2025",
    imglg: "/home/annual-team-meeting-lg.webp",
    imgsm: "/home/annual-team-meeting-sm.webp",
    alt: "Dahab Miners team gathering at Annual Meeting 2025 in Al Raha Creek, Abu Dhabi, celebrating milestones in Bitcoin mining across UAE and Ethiopia.",
    title: "ANNUAL TEAM MEETING",
    date: "Nov 6, 2025",
    location: "Al Raha Creek, Abu Dhabi",
    p1: "Dahab Miners Annual Team Meet — Al Raha Creek, Abu Dhabi | November 6, 2024",
    p2: "On November 6, 2024, Dahab Miners held its Annual Team Meet at the beautiful Al Raha Creek in Abu Dhabi, bringing together team members from across the region to celebrate the company’s achievements and align on future goals.",
    p3: "This special gathering provided a valuable opportunity for our leadership, operations, and support teams to reflect on a year of remarkable growth — from key milestones in Ethiopia and the UAE to strategic partnerships that have further solidified Dahab Miners as a trusted name in global Bitcoin mining solutions. ",
    p4: "The event included: • An annual business performance review • Vision and roadmap discussions for 2025 and beyond • Recognition of outstanding team contributions • A relaxing and enjoyable dinner to strengthen team spirit and camaraderie Our Annual Team Meet reflects Dahab Miners’ commitment to fostering a unified, motivated, and mission-driven organization that continues to push the boundaries of innovation and service in the Bitcoin mining industry.",
  },
  {
    id: 5,
    slug: "bitcoin-summit-ethiopia-2025-dahab-miners-app-launch",
    imglg: "/home/dahab-app-launch-lg.webp",
    imgsm: "/home/dahab-app-launch-lg.webp",
    alt: "Dahab Miners team at Bitcoin Summit Ethiopia 2025 representing Bitcoin mining in UAE.",
    title: "Dahab Miners App Launches at Bitcoin Summit Ethiopia 2025",
    date: "Sep 16, 2025",
    location: "Addis Ababa, Ethiopia",
    p1: "On September 16, 2025, the Dahab Miners team proudly unveiled the Dahab Miners App at the Bitcoin Summit Ethiopia 2025, held in Addis Ababa — a landmark gathering that brought together global innovators, miners, investors, and policymakers to shape the future of sustainable Bitcoin mining in Africa and beyond.",
    p2: "This moment marked a defining milestone in Dahab Miners’ journey not merely as a launch of a digital product, but as a statement of purpose: to make Bitcoin mining accessible, transparent, and environmentally responsible for everyone, everywhere.",
    p3: "Since its inception, Bitcoin has represented freedom, fairness, and decentralization. Yet, over time, access to mining has become increasingly concentrated in the hands of large institutions. At Dahab Miners, we believe that mining should once again belong to the people to individuals, dreamers, and believers who want to be part of Bitcoin’s real foundation: the network itself.",
    p4: "The Dahab Miners App was created to bridge that gap. It allows anyone from beginners to enthusiasts to own a share of real, hardware-backed Bitcoin mining, powered by clean energy from Ethiopia and the UAE. Through this, Dahab Miners makes Bitcoin mining simpler, smarter, and greener, without compromising on transparency or performance.",
    p5: "Choosing Ethiopia as the stage for this global debut was both strategic and deeply symbolic. Ethiopia is one of the world’s most promising frontiers for renewable energy, blessed with abundant hydropower potential and a rapidly growing blockchain ecosystem. By launching the Dahab Miners App in Addis Ababa, Dahab reaffirmed its commitment to empowering the world through Ethiopia’s Green Hashrate, a model that promotes responsible energy use while fueling digital growth across borders.",
    p6: "It’s not just about mining Bitcoin. It’s about creating jobs, building infrastructure, and sharing prosperity where technological innovation meets sustainable impact.",
    p7: "During the summit, Rushil Kamarudheen, Chief Operating Officer of Dahab Miners, delivered a keynote address titled: 'Empowering the World with Ethiopia’s Green Hashrate.' In his session, Rushil highlighted how the convergence of renewable energy and blockchain technology can redefine not only how Bitcoin is mined but also how nations can harness it for economic growth and empowerment.",
    p8: "His address resonated deeply with the audience, reinforcing Dahab’s role as a bridge between innovation and sustainability, between Africa and the world.",
    p9: "The Dahab Miners App is more than a mining platform it's a gateway to the decentralized economy. Users can now participate in Bitcoin mining without the challenges of setup, logistics, or high energy costs. Every miner on the platform is real, hardware-backed, and powered by renewable sources, with earnings distributed transparently based on ownership share.",
    p10: "It represents a new chapter for Bitcoin mining one that’s open, ethical, and sustainable. With every block mined, Dahab Miners move closer to a cleaner, smarter, and more inclusive digital future.",
  },
  {
    id: 6,
    slug: "bitplebs-summit-goa-2025-sustainable-mining",
    imglg: "/home/bitplebs-summit-goa-lg.webp",
    imgsm: "/home/bitplebs-summit-goa-lg.webp",
    alt: "Dahab Miners team at BitPlebs Summit Goa 2025 discussing sustainable Bitcoin mining in India.",
    title: " BitPlebs Summit Goa ",
    date: "Nov 1, 2025",
    location: "Benaulim, Goa",
    p1: "On November 1, 2025, Dahab Miners participated in the BitPlebs Summit held in Benaulim, Goa - a gathering focused on India's growing Bitcoin ecosystem and the future of mining education, infrastructure, and adoption.",
    p2: 'During the event, Rushil Kamarudheen, Chief Operating Officer of Dahab Miners, joined a fireside chat titled "Sovereign Mining Lessons from Bhutan & Ethiopia." The session brought together industry builders to discuss how different regions are developing sustainable and responsible Bitcoin mining models.',
    p3: "Rushil shared practical insights from Dahab Miners' work in Ethiopia and the UAE, including how renewable energy can support long-term Bitcoin mining growth, lessons from hydropower-based mining environments, how transparent and efficient operations help build trust in mining, and the role the UAE is playing in miner hosting, repair, and infrastructure development. His contribution helped highlight how mining can be built responsibly by aligning energy availability, operational efficiency, and local economic development.",
    p4: "Dahab Miners' presence at the BitPlebs Summit reflects our ongoing commitment to supporting Bitcoin mining infrastructure, promoting sustainable mining practices, and contributing to the growth of the wider Bitcoin community in India and beyond.",
    p5: "This event marks another step in our goal to create reliable, renewable-powered, and globally connected mining ecosystems.",
  },
  {
    id: 7,
    slug: "hashsouq-bitcoin-ai-compute-event-uae",
    imglg: "/home/hash-souq-abu-dhabi-lg.webp",
    imgsm: "/home/hash-souq-abu-dhabi-sm.webp",
    images: [
      "/home/hash-souq-img-1.webp",
      "/home/hash-souq-img-2.webp",
      "/home/hash-souq-img-3.webp",
      "/home/hash-souq-img-4.webp",
      "/home/hash-souq-img-5.webp",
      "/home/hash-souq-img-6.webp",
      "/home/hash-souq-img-7.webp",
    ],
    btmimg: "/home/hash-souq-btm.webp",
    alt: "HASHSOUQ Abu Dhabi 2025 hosted by Dahab Miners and Morphware AI showcasing AI and Bitcoin computing power.",
    title: "HASHSOUQ by Dahab",
    date: "Dec 7, 2025",
    hosted: "Dahab Miners × Morphware AI",
    location: "Saadiyat Rotana, Abu Dhabi",
    p1: "On December 7, 2025, Dahab Miners Group hosted HASHSOUQ at Saadiyat Rotana, Abu Dhabi - an invite-only gathering designed to simplify the worlds of AI, Bitcoin, and computing power for new and experienced attendees alike. The event brought together leading experts in AI compute, mining hardware, energy infrastructure, and datacenter engineering to give the UAE community a clear picture of the technologies shaping the next decade.",
    p2: "HASHSOUQ was created for anyone who has heard about AI or Bitcoin but wanted a practical, beginner-friendly explanation of how these systems work in real life. Speakers from Morphware AI, DEMA Energy, Uminers, and Dahab Group discussed the future of computing power, why Bitcoin has become a global digital asset, and how the UAE is positioned to become a major center for compute-driven industries.",
    p3: "Throughout the event, attendees explored hands-on demo zones showcasing silent boxes, hydro-cooling systems, home-mining setups, and the latest hardware from global mining companies. Dahab also presented the Dahab Mining App, a platform that provides instant terahash access with daily Bitcoin rewards, designed for people entering mining without technical setup.",
    p4: "A multi-company panel featuring representatives from MicroBT, Bitdeer, ViaBTC, and Morphware highlighted why computing power is emerging as a strategic resource and what opportunities are available for UAE residents and investors. The event concluded with an Emirati-only Silent Box giveaway and a closing session on Dahab's long-term role in the UAE's compute and mining ecosystem.",
    p5: "The event saw participation from a wide range of global and regional companies including Dahab Miners, Dahab Mining App, Dahab Engineering, Morphware AI, Tron Technologies, ViaBTC, AmityAge, Hive OS, Hashera, Uminers, Bitdeer, Ourpool, BTCPAY, MicroBT, Gigablock Cryptocurrency mining solutions, Ciphertech, Dema Energy, Laith Electro Mechanical, 3U, and Guardians of Bitcoin - creating a comprehensive showcase of the technologies and teams driving the future of compute power.",
    p6: "HASHSOUQ marks a significant step forward as Dahab continues shaping the region's future of AI, compute power, and Bitcoin mining.",
    btmdesc:
      "Panel Discussion at HASH SOUQ by Dahab The panel featured industry leaders Khurram Bin Kamal (COO, Morphware AI), Alice Chun Zhang (Senior Business Development Manager, MicroBT), Sharif Allayarov (Sales Director, Bitdeer), and Juli Rudencova (Head of ViaBTC), who shared insights on the future of computing power, Bitcoin mining infrastructure, and the UAE’s role in the global AI and digital asset ecosystem",
  },
];
